export const ENGAGE_MODEL = `
query{
    hireStrapiDeveloper{
      data{
        id
        attributes{
          engagement_model{
            data{
              id
              attributes{
                MainTitle{
                  id
                  Title
                  Description
                }
                MultilistData{
                  id
                  Title
                  Description
                }
              }
            }
          }
        }
      }
    }
  }
`;

export const AVAILABILITY = `
query{
    hireStrapiDeveloper{
      data{
        id
        attributes{
          availability{
            data{
              id
              attributes{
                Availability{
                  id
                  Title
                  SubTitle
                  Body
                  Description
                  Images{
                    data{
                      id
                      attributes{
                        alternativeText
                        url
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
`;
export const HIRE_TAB_QUERY = `
query{
  hireStrapiDeveloper{
    data{
      id
      attributes{
        hire_tab_component{
          data{
            id
            attributes{
              TitleData{
                id
                Title
                Description
              }
              TabData{
                id
                Title
                Description
                Image{
                  data{
                    id
                    attributes
                    {
                      url
                      alternativeText
                    }
                  }
                }
                Link{
                  id
                  href
                  label
                }
              }
            }
          }
        }
      }
    }
  }
}
`;
